pipeline {
    agent any

    tools {
        nodejs('NodeJs')
    }

    parameters {
        string(name: 'SPEC', defaultValue: "cypress/e2e/Tests/**/*.feature", description: 'Cypress test spec file or folder')
        choice(name: 'BROWSER', choices: ['chrome', 'edge'], description: 'Browser to run tests in')
    }

    stages {
        stage('Checkout Code') {
            steps {
                // Checkout code from version control
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                // Install project dependencies
                sh 'cd cypress-cucumber/ && npm install'                
            }
        }

        stage('Testing') {
            steps {
                // Run Cypress tests
                sh 'cd cypress-cucumber/ && npx cypress run --spec "${SPEC}" --browser "${BROWSER}" --headless'
            }
        }
    }

    post {
        always {
            // Archive test results and screenshots
            archiveArtifacts artifacts: 'cypress/screenshots/**/*, cypress/videos/**/*', allowEmptyArchive: true
            junit 'cypress/results/*.xml' // If you generate test result reports
        }
        failure {
            // Notify on failure
            echo 'Cypress tests failed!'
        }
    }
}
